import type { ImageMetadata } from 'astro';

/*
 * Resolves media referenced in work frontmatter (paths relative to
 * src/assets/works/<slug>/) to build-time assets.
 * Images go through astro:assets (resized, srcset); videos are copied as-is
 * with their `.thumb.jpg` poster generated by the content tool.
 */

const images = import.meta.glob<ImageMetadata>(
  '/src/assets/works/*/*.{webp,jpg,jpeg,png,avif,gif}',
  { eager: true, import: 'default' },
);

const videos = import.meta.glob<string>(
  '/src/assets/works/*/*.{webm,mp4}',
  { eager: true, query: '?url', import: 'default' },
);

export type ResolvedMedia =
  | { type: 'image'; image: ImageMetadata }
  | { type: 'video'; url: string; poster?: ImageMetadata };

const keyFor = (slug: string, file: string) => `/src/assets/works/${slug}/${file}`;

export function resolveMedia(slug: string, file: string, type: 'image' | 'video'): ResolvedMedia {
  if (type === 'image') {
    const image = images[keyFor(slug, file)];
    if (!image) throw new Error(`[media] Image not found: src/assets/works/${slug}/${file}`);
    return { type: 'image', image };
  }
  const url = videos[keyFor(slug, file)];
  if (!url) throw new Error(`[media] Video not found: src/assets/works/${slug}/${file}`);
  const poster = images[keyFor(slug, file.replace(/\.[^.]+$/, '.thumb.jpg'))];
  return { type: 'video', url, poster };
}
